"""Migration: `Add Buckets and Fruits tables`.

Revision ID: 8a7c17293255
Revises: 5d8543e59b01
Create Date: 2026-02-16 20:11:08.869764+00:00
"""
# pyright: reportAttributeAccessIssue=false

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8a7c17293255"
down_revision: str | Sequence[str] | None = "5d8543e59b01"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "buckets",
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fruits",
        sa.Column(
            "name", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("bucket_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "expires_at > created_at",
            name="check_expires_at_after_created_at",
        ),
        sa.ForeignKeyConstraint(
            ["bucket_id"],
            ["buckets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###

    # Create trigger function to validate fruit.user_id and fruit.bucket.user_id match
    op.execute("""
        CREATE OR REPLACE FUNCTION bucket_user_id_matches_fruit_user_id()
        RETURNS TRIGGER AS $$
        BEGIN
            IF NEW.bucket_id IS NOT NULL THEN
                IF (SELECT user_id FROM buckets WHERE id = NEW.bucket_id) != NEW.user_id THEN
                    RAISE EXCEPTION 'fruit.user_id must match fruit.bucket.user_id';
                END IF;
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)

    # Create deferrable constraint trigger. Only ran pre-commit, so it doesn't
    # interfere with normal operations within the transaction, but still
    # ensures data integrity at commit.
    op.execute("""
        CREATE CONSTRAINT TRIGGER fruit_bucket_user_match_trigger
        AFTER INSERT OR UPDATE ON fruits
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW
        EXECUTE FUNCTION bucket_user_id_matches_fruit_user_id()
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(
        "DROP TRIGGER IF EXISTS fruit_bucket_user_match_trigger ON fruits"
    )
    op.execute(
        "DROP FUNCTION IF EXISTS bucket_user_id_matches_fruit_user_id()"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fruits")
    op.drop_table("buckets")
    # ### end Alembic commands ###
