"""Migration: `Add Buckets and Fruits tables`.

Revision ID: 8a7c17293255
Revises: 5d8543e59b01
Create Date: 2026-02-16 20:11:08.869764+00:00
"""
# pyright: reportAttributeAccessIssue=false

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8a7c17293255"
down_revision: str | Sequence[str] | None = "5d8543e59b01"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "buckets",
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fruits",
        sa.Column(
            "name", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("bucket_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("expires_at >= created_at + interval '1 second'"),
        sa.ForeignKeyConstraint(
            ["bucket_id"],
            ["buckets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fruits")
    op.drop_table("buckets")
    # ### end Alembic commands ###
